{:user {:plugins [[lein-ancient "0.6.14"]
                  [cider/cider-nrepl "0.15.1"]
                  [refactor-nrepl "2.3.1"]
                  [slamhound "1.5.5"]
                  [lein-try "0.4.3"]
                  [lein-exec "0.3.6"]
                  [lein-kibit "0.1.5"]
                  [jonase/eastwood "0.2.4"]
                  [lein-bikeshed "0.4.1"]
                  [lein-nvd "0.4.0"]
                  [lein-cloverage "1.0.9"]]}}
